version: '3.8'
services:
  ai-artistic-style-service:
    image: urmsandeep/ai-artistic-style-service:latest
    container_name: ai-artistic-style
    ports:
      - "5001:5001"
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
